title: UnitVectorY Labs Blog
description: >-
  The latest updates from UnitVectorY Labs.
baseurl: "/uvy-labs-blog"
url: "https://unitvectory-labs.github.io"

author: Jared Hatfield
github_username: UnitVectorY-Labs
rss: RSS

# Navigation header links
header_pages:
  - about.md
  - tags.md

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

show_excerpts: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "UnitVectorY Labs"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
  - .sass-cache/
  - _site/
